//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IB150218_APII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izlazi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Izlazi()
        {
            this.IzlaziStavkes = new HashSet<IzlaziStavke>();
        }
    
        public int IzlaziID { get; set; }
        public Nullable<int> NarudzbaID { get; set; }
        public Nullable<decimal> IznosSaPDV { get; set; }
        public Nullable<decimal> IznosBezPDV { get; set; }
        public Nullable<int> KorisnikID { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Narudzbe Narudzbe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzlaziStavke> IzlaziStavkes { get; set; }
    }
}
