//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IB150218_APII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzlaziStavke
    {
        public int IzlazStavkeID { get; set; }
        public Nullable<int> ProizvodID { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public Nullable<decimal> Cijena { get; set; }
        public Nullable<bool> Status { get; set; }
        public int IzlaziID { get; set; }
    
        public virtual Izlazi Izlazi { get; set; }
        public virtual Proizvodi Proizvodi { get; set; }
    }
}
