//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IB150218_APII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meni
    {
        public int MenidID { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public Nullable<int> KorisnikID { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
    }
}
