//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IB150218_APII.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eProdajaEntities : DbContext
    {
        public eProdajaEntities()
            : base("name=eProdajaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Izlazi> Izlazis { get; set; }
        public virtual DbSet<IzlaziStavke> IzlaziStavkes { get; set; }
        public virtual DbSet<JediniceMjere> JediniceMjeres { get; set; }
        public virtual DbSet<Korisnici> Korisnicis { get; set; }
        public virtual DbSet<Kupci> Kupcis { get; set; }
        public virtual DbSet<Meni> Menis { get; set; }
        public virtual DbSet<NarudzbaStavke> NarudzbaStavkes { get; set; }
        public virtual DbSet<Narudzbe> Narudzbes { get; set; }
        public virtual DbSet<Ocjene> Ocjenes { get; set; }
        public virtual DbSet<Proizvodi> Proizvodis { get; set; }
        public virtual DbSet<Uloge> Uloges { get; set; }
        public virtual DbSet<VrsteProizvoda> VrsteProizvodas { get; set; }
    
        public virtual int AllDobavljaci()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AllDobavljaci");
        }
    
        public virtual ObjectResult<AllKorisnici_Result> AllKorisnici()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllKorisnici_Result>("AllKorisnici");
        }
    
        public virtual ObjectResult<Allmeni_Result> Allmeni()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Allmeni_Result>("Allmeni");
        }
    
        public virtual ObjectResult<AllProizvodi_Result> AllProizvodi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllProizvodi_Result>("AllProizvodi");
        }
    
        public virtual ObjectResult<AllProizvodiByVrstaMobile_Result> AllProizvodiByVrstaMobile(Nullable<int> vrstaID)
        {
            var vrstaIDParameter = vrstaID.HasValue ?
                new ObjectParameter("VrstaID", vrstaID) :
                new ObjectParameter("VrstaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllProizvodiByVrstaMobile_Result>("AllProizvodiByVrstaMobile", vrstaIDParameter);
        }
    
        public virtual ObjectResult<AllProizvodiForAdd3_Result> AllProizvodiForAdd3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllProizvodiForAdd3_Result>("AllProizvodiForAdd3");
        }
    
        public virtual ObjectResult<AllProizvodiMobile_Result> AllProizvodiMobile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllProizvodiMobile_Result>("AllProizvodiMobile");
        }
    
        public virtual int delete_izlazi(Nullable<int> korisnikID)
        {
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("korisnikID", korisnikID) :
                new ObjectParameter("korisnikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_izlazi", korisnikIDParameter);
        }
    
        public virtual int delete_izlazi1(Nullable<int> korisnikID)
        {
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("korisnikID", korisnikID) :
                new ObjectParameter("korisnikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_izlazi1", korisnikIDParameter);
        }
    
        public virtual int delete_korisnici(Nullable<int> korisnikID)
        {
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("korisnikID", korisnikID) :
                new ObjectParameter("korisnikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_korisnici", korisnikIDParameter);
        }
    
        public virtual int delete_meni(Nullable<int> korisnikID)
        {
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("korisnikID", korisnikID) :
                new ObjectParameter("korisnikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_meni", korisnikIDParameter);
        }
    
        public virtual int DeleteMeni(Nullable<int> menidID)
        {
            var menidIDParameter = menidID.HasValue ?
                new ObjectParameter("MenidID", menidID) :
                new ObjectParameter("MenidID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteMeni", menidIDParameter);
        }
    
        public virtual ObjectResult<esp_AllNarudzbe_DateOdDateDo_Result> esp_AllNarudzbe_DateOdDateDo(Nullable<System.DateTime> datumOd, Nullable<System.DateTime> datumDo)
        {
            var datumOdParameter = datumOd.HasValue ?
                new ObjectParameter("datumOd", datumOd) :
                new ObjectParameter("datumOd", typeof(System.DateTime));
    
            var datumDoParameter = datumDo.HasValue ?
                new ObjectParameter("datumDo", datumDo) :
                new ObjectParameter("datumDo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_AllNarudzbe_DateOdDateDo_Result>("esp_AllNarudzbe_DateOdDateDo", datumOdParameter, datumDoParameter);
        }
    
        public virtual int esp_Dobavljaci_SelectByNaziv(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_Dobavljaci_SelectByNaziv", nazivParameter);
        }
    
        public virtual ObjectResult<esp_HistorijaNarudzbiByKupacID_Result> esp_HistorijaNarudzbiByKupacID(Nullable<int> kupacID)
        {
            var kupacIDParameter = kupacID.HasValue ?
                new ObjectParameter("KupacID", kupacID) :
                new ObjectParameter("KupacID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_HistorijaNarudzbiByKupacID_Result>("esp_HistorijaNarudzbiByKupacID", kupacIDParameter);
        }
    
        public virtual int esp_Izlazi_InsertByNarudzbaID(Nullable<int> narudzbaID, Nullable<decimal> iznosSaPDV, Nullable<decimal> iznosBezPDV, Nullable<int> korisnikID)
        {
            var narudzbaIDParameter = narudzbaID.HasValue ?
                new ObjectParameter("NarudzbaID", narudzbaID) :
                new ObjectParameter("NarudzbaID", typeof(int));
    
            var iznosSaPDVParameter = iznosSaPDV.HasValue ?
                new ObjectParameter("IznosSaPDV", iznosSaPDV) :
                new ObjectParameter("IznosSaPDV", typeof(decimal));
    
            var iznosBezPDVParameter = iznosBezPDV.HasValue ?
                new ObjectParameter("IznosBezPDV", iznosBezPDV) :
                new ObjectParameter("IznosBezPDV", typeof(decimal));
    
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("KorisnikID", korisnikID) :
                new ObjectParameter("KorisnikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_Izlazi_InsertByNarudzbaID", narudzbaIDParameter, iznosSaPDVParameter, iznosBezPDVParameter, korisnikIDParameter);
        }
    
        public virtual int esp_Iznos(Nullable<int> kupacID)
        {
            var kupacIDParameter = kupacID.HasValue ?
                new ObjectParameter("KupacID", kupacID) :
                new ObjectParameter("KupacID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_Iznos", kupacIDParameter);
        }
    
        public virtual int esp_Iznos2(Nullable<int> kupacID)
        {
            var kupacIDParameter = kupacID.HasValue ?
                new ObjectParameter("KupacID", kupacID) :
                new ObjectParameter("KupacID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_Iznos2", kupacIDParameter);
        }
    
        public virtual int esp_Iznos3(Nullable<int> kupacID)
        {
            var kupacIDParameter = kupacID.HasValue ?
                new ObjectParameter("KupacID", kupacID) :
                new ObjectParameter("KupacID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_Iznos3", kupacIDParameter);
        }
    
        public virtual ObjectResult<esp_JediniceMjere_SelectAll_Result> esp_JediniceMjere_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_JediniceMjere_SelectAll_Result>("esp_JediniceMjere_SelectAll");
        }
    
        public virtual ObjectResult<Nullable<decimal>> esp_Korisnici_Insert(string ime, string prezime, string email, string telefon, string korisnickoIme, string lozinkaSalt, string lozinkaHash, Nullable<int> ulogeID)
        {
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaSaltParameter = lozinkaSalt != null ?
                new ObjectParameter("LozinkaSalt", lozinkaSalt) :
                new ObjectParameter("LozinkaSalt", typeof(string));
    
            var lozinkaHashParameter = lozinkaHash != null ?
                new ObjectParameter("LozinkaHash", lozinkaHash) :
                new ObjectParameter("LozinkaHash", typeof(string));
    
            var ulogeIDParameter = ulogeID.HasValue ?
                new ObjectParameter("ulogeID", ulogeID) :
                new ObjectParameter("ulogeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("esp_Korisnici_Insert", imeParameter, prezimeParameter, emailParameter, telefonParameter, korisnickoImeParameter, lozinkaSaltParameter, lozinkaHashParameter, ulogeIDParameter);
        }
    
        public virtual ObjectResult<esp_Korisnici_SelectByImePrezime_Result> esp_Korisnici_SelectByImePrezime(string imePrezime)
        {
            var imePrezimeParameter = imePrezime != null ?
                new ObjectParameter("ImePrezime", imePrezime) :
                new ObjectParameter("ImePrezime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Korisnici_SelectByImePrezime_Result>("esp_Korisnici_SelectByImePrezime", imePrezimeParameter);
        }
    
        public virtual ObjectResult<esp_Korisnici_SelectByKorisnickoIme_Result> esp_Korisnici_SelectByKorisnickoIme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Korisnici_SelectByKorisnickoIme_Result>("esp_Korisnici_SelectByKorisnickoIme", usernameParameter);
        }
    
        public virtual int esp_Korisnici_Update(Nullable<int> korisnikID, string ime, string prezime, string email, string telefon, string korisnickoIme, string lozinkaSalt, string lozinkaHash, Nullable<bool> status, Nullable<int> ulogaID)
        {
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("KorisnikID", korisnikID) :
                new ObjectParameter("KorisnikID", typeof(int));
    
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaSaltParameter = lozinkaSalt != null ?
                new ObjectParameter("LozinkaSalt", lozinkaSalt) :
                new ObjectParameter("LozinkaSalt", typeof(string));
    
            var lozinkaHashParameter = lozinkaHash != null ?
                new ObjectParameter("LozinkaHash", lozinkaHash) :
                new ObjectParameter("LozinkaHash", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var ulogaIDParameter = ulogaID.HasValue ?
                new ObjectParameter("UlogaID", ulogaID) :
                new ObjectParameter("UlogaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_Korisnici_Update", korisnikIDParameter, imeParameter, prezimeParameter, emailParameter, telefonParameter, korisnickoImeParameter, lozinkaSaltParameter, lozinkaHashParameter, statusParameter, ulogaIDParameter);
        }
    
        public virtual int esp_KorisniciUloge_Insert(Nullable<int> korisnikID, Nullable<int> ulogaID)
        {
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("KorisnikID", korisnikID) :
                new ObjectParameter("KorisnikID", typeof(int));
    
            var ulogaIDParameter = ulogaID.HasValue ?
                new ObjectParameter("UlogaID", ulogaID) :
                new ObjectParameter("UlogaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_KorisniciUloge_Insert", korisnikIDParameter, ulogaIDParameter);
        }
    
        public virtual ObjectResult<esp_KorisnikByID_Result> esp_KorisnikByID(Nullable<int> korinskikID)
        {
            var korinskikIDParameter = korinskikID.HasValue ?
                new ObjectParameter("korinskikID", korinskikID) :
                new ObjectParameter("korinskikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_KorisnikByID_Result>("esp_KorisnikByID", korinskikIDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> esp_Kupci_Insert(string ime, string prezime, string email, string korisnickoIme, string lozinkaSalt, string lozinkaHash)
        {
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaSaltParameter = lozinkaSalt != null ?
                new ObjectParameter("LozinkaSalt", lozinkaSalt) :
                new ObjectParameter("LozinkaSalt", typeof(string));
    
            var lozinkaHashParameter = lozinkaHash != null ?
                new ObjectParameter("LozinkaHash", lozinkaHash) :
                new ObjectParameter("LozinkaHash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("esp_Kupci_Insert", imeParameter, prezimeParameter, emailParameter, korisnickoImeParameter, lozinkaSaltParameter, lozinkaHashParameter);
        }
    
        public virtual ObjectResult<esp_Kupci_SelectByKorisnickoIme_Result> esp_Kupci_SelectByKorisnickoIme(string korisnickoIme)
        {
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Kupci_SelectByKorisnickoIme_Result>("esp_Kupci_SelectByKorisnickoIme", korisnickoImeParameter);
        }
    
        public virtual ObjectResult<esp_KupciAll_Result> esp_KupciAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_KupciAll_Result>("esp_KupciAll");
        }
    
        public virtual ObjectResult<esp_KupciSelectByKorisnickoIme_Result> esp_KupciSelectByKorisnickoIme(string korisnickoIme)
        {
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_KupciSelectByKorisnickoIme_Result>("esp_KupciSelectByKorisnickoIme", korisnickoImeParameter);
        }
    
        public virtual int esp_NarudzbaStavke_Insert(Nullable<int> narudzbaID, Nullable<int> proizvodID, Nullable<int> kolicina)
        {
            var narudzbaIDParameter = narudzbaID.HasValue ?
                new ObjectParameter("NarudzbaID", narudzbaID) :
                new ObjectParameter("NarudzbaID", typeof(int));
    
            var proizvodIDParameter = proizvodID.HasValue ?
                new ObjectParameter("ProizvodID", proizvodID) :
                new ObjectParameter("ProizvodID", typeof(int));
    
            var kolicinaParameter = kolicina.HasValue ?
                new ObjectParameter("Kolicina", kolicina) :
                new ObjectParameter("Kolicina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_NarudzbaStavke_Insert", narudzbaIDParameter, proizvodIDParameter, kolicinaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> esp_Narudzbe_CountAktivne()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("esp_Narudzbe_CountAktivne");
        }
    
        public virtual ObjectResult<Nullable<decimal>> esp_Narudzbe_Insert(string brojNarudzbe, Nullable<int> kupacID, Nullable<System.DateTime> datum)
        {
            var brojNarudzbeParameter = brojNarudzbe != null ?
                new ObjectParameter("BrojNarudzbe", brojNarudzbe) :
                new ObjectParameter("BrojNarudzbe", typeof(string));
    
            var kupacIDParameter = kupacID.HasValue ?
                new ObjectParameter("KupacID", kupacID) :
                new ObjectParameter("KupacID", typeof(int));
    
            var datumParameter = datum.HasValue ?
                new ObjectParameter("Datum", datum) :
                new ObjectParameter("Datum", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("esp_Narudzbe_Insert", brojNarudzbeParameter, kupacIDParameter, datumParameter);
        }
    
        public virtual ObjectResult<esp_Narudzbe_SelectAktivne_Result> esp_Narudzbe_SelectAktivne()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Narudzbe_SelectAktivne_Result>("esp_Narudzbe_SelectAktivne");
        }
    
        public virtual ObjectResult<esp_NarudzbeByPeriodProizvod_Result> esp_NarudzbeByPeriodProizvod(Nullable<System.DateTime> datumOd, Nullable<System.DateTime> datumDo, Nullable<int> proizvodId)
        {
            var datumOdParameter = datumOd.HasValue ?
                new ObjectParameter("DatumOd", datumOd) :
                new ObjectParameter("DatumOd", typeof(System.DateTime));
    
            var datumDoParameter = datumDo.HasValue ?
                new ObjectParameter("DatumDo", datumDo) :
                new ObjectParameter("DatumDo", typeof(System.DateTime));
    
            var proizvodIdParameter = proizvodId.HasValue ?
                new ObjectParameter("ProizvodId", proizvodId) :
                new ObjectParameter("ProizvodId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_NarudzbeByPeriodProizvod_Result>("esp_NarudzbeByPeriodProizvod", datumOdParameter, datumDoParameter, proizvodIdParameter);
        }
    
        public virtual ObjectResult<esp_NarudzbeStavke_SelectByNarudzbaID_Result> esp_NarudzbeStavke_SelectByNarudzbaID(Nullable<int> narudzbaID)
        {
            var narudzbaIDParameter = narudzbaID.HasValue ?
                new ObjectParameter("NarudzbaID", narudzbaID) :
                new ObjectParameter("NarudzbaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_NarudzbeStavke_SelectByNarudzbaID_Result>("esp_NarudzbeStavke_SelectByNarudzbaID", narudzbaIDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> esp_Proizvodi_Insert(string naziv, string sifra, Nullable<decimal> cijena, Nullable<int> vrstaID, Nullable<int> jedinicaMjereID, byte[] slika, byte[] slikaThumb)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var sifraParameter = sifra != null ?
                new ObjectParameter("Sifra", sifra) :
                new ObjectParameter("Sifra", typeof(string));
    
            var cijenaParameter = cijena.HasValue ?
                new ObjectParameter("Cijena", cijena) :
                new ObjectParameter("Cijena", typeof(decimal));
    
            var vrstaIDParameter = vrstaID.HasValue ?
                new ObjectParameter("VrstaID", vrstaID) :
                new ObjectParameter("VrstaID", typeof(int));
    
            var jedinicaMjereIDParameter = jedinicaMjereID.HasValue ?
                new ObjectParameter("JedinicaMjereID", jedinicaMjereID) :
                new ObjectParameter("JedinicaMjereID", typeof(int));
    
            var slikaParameter = slika != null ?
                new ObjectParameter("Slika", slika) :
                new ObjectParameter("Slika", typeof(byte[]));
    
            var slikaThumbParameter = slikaThumb != null ?
                new ObjectParameter("SlikaThumb", slikaThumb) :
                new ObjectParameter("SlikaThumb", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("esp_Proizvodi_Insert", nazivParameter, sifraParameter, cijenaParameter, vrstaIDParameter, jedinicaMjereIDParameter, slikaParameter, slikaThumbParameter);
        }
    
        public virtual ObjectResult<esp_Proizvodi_SelectById_Result> esp_Proizvodi_SelectById(Nullable<int> proizvodID)
        {
            var proizvodIDParameter = proizvodID.HasValue ?
                new ObjectParameter("ProizvodID", proizvodID) :
                new ObjectParameter("ProizvodID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Proizvodi_SelectById_Result>("esp_Proizvodi_SelectById", proizvodIDParameter);
        }
    
        public virtual ObjectResult<esp_Proizvodi_SelectBySifra_Result> esp_Proizvodi_SelectBySifra(string sifra)
        {
            var sifraParameter = sifra != null ?
                new ObjectParameter("Sifra", sifra) :
                new ObjectParameter("Sifra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Proizvodi_SelectBySifra_Result>("esp_Proizvodi_SelectBySifra", sifraParameter);
        }
    
        public virtual ObjectResult<esp_Proizvodi_SelectByVrsta_Result> esp_Proizvodi_SelectByVrsta(Nullable<int> vrstaID)
        {
            var vrstaIDParameter = vrstaID.HasValue ?
                new ObjectParameter("VrstaID", vrstaID) :
                new ObjectParameter("VrstaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Proizvodi_SelectByVrsta_Result>("esp_Proizvodi_SelectByVrsta", vrstaIDParameter);
        }
    
        public virtual int esp_ProizvodiByKupacID(Nullable<int> kupacID)
        {
            var kupacIDParameter = kupacID.HasValue ?
                new ObjectParameter("KupacID", kupacID) :
                new ObjectParameter("KupacID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_ProizvodiByKupacID", kupacIDParameter);
        }
    
        public virtual int esp_ProizvodiByNarudzbaId2(Nullable<int> narudzbaID)
        {
            var narudzbaIDParameter = narudzbaID.HasValue ?
                new ObjectParameter("NarudzbaID", narudzbaID) :
                new ObjectParameter("NarudzbaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_ProizvodiByNarudzbaId2", narudzbaIDParameter);
        }
    
        public virtual ObjectResult<esp_selectfromProizvodiByProizvodId_Result> esp_selectfromProizvodiByProizvodId(Nullable<int> proizvodID)
        {
            var proizvodIDParameter = proizvodID.HasValue ?
                new ObjectParameter("ProizvodID", proizvodID) :
                new ObjectParameter("ProizvodID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_selectfromProizvodiByProizvodId_Result>("esp_selectfromProizvodiByProizvodId", proizvodIDParameter);
        }
    
        public virtual ObjectResult<esp_selectFromProizvodiByVrstaId_Result> esp_selectFromProizvodiByVrstaId(Nullable<int> vrstaID, Nullable<int> mjeraID)
        {
            var vrstaIDParameter = vrstaID.HasValue ?
                new ObjectParameter("VrstaID", vrstaID) :
                new ObjectParameter("VrstaID", typeof(int));
    
            var mjeraIDParameter = mjeraID.HasValue ?
                new ObjectParameter("mjeraID", mjeraID) :
                new ObjectParameter("mjeraID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_selectFromProizvodiByVrstaId_Result>("esp_selectFromProizvodiByVrstaId", vrstaIDParameter, mjeraIDParameter);
        }
    
        public virtual ObjectResult<esp_selectFromProizvodiByVrstaMjeraId1_Result> esp_selectFromProizvodiByVrstaMjeraId1(Nullable<int> vrstaID, Nullable<int> mjeraID)
        {
            var vrstaIDParameter = vrstaID.HasValue ?
                new ObjectParameter("VrstaID", vrstaID) :
                new ObjectParameter("VrstaID", typeof(int));
    
            var mjeraIDParameter = mjeraID.HasValue ?
                new ObjectParameter("mjeraID", mjeraID) :
                new ObjectParameter("mjeraID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_selectFromProizvodiByVrstaMjeraId1_Result>("esp_selectFromProizvodiByVrstaMjeraId1", vrstaIDParameter, mjeraIDParameter);
        }
    
        public virtual ObjectResult<esp_selectFromProizvodiReport_Result> esp_selectFromProizvodiReport(Nullable<int> vrstaID, Nullable<int> mjeraID)
        {
            var vrstaIDParameter = vrstaID.HasValue ?
                new ObjectParameter("VrstaID", vrstaID) :
                new ObjectParameter("VrstaID", typeof(int));
    
            var mjeraIDParameter = mjeraID.HasValue ?
                new ObjectParameter("mjeraID", mjeraID) :
                new ObjectParameter("mjeraID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_selectFromProizvodiReport_Result>("esp_selectFromProizvodiReport", vrstaIDParameter, mjeraIDParameter);
        }
    
        public virtual int esp_StavkeIzlazaByIzlaziID(Nullable<int> izlazID)
        {
            var izlazIDParameter = izlazID.HasValue ?
                new ObjectParameter("IzlazID", izlazID) :
                new ObjectParameter("IzlazID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_StavkeIzlazaByIzlaziID", izlazIDParameter);
        }
    
        public virtual ObjectResult<esp_Uloge_SelectAll_Result> esp_Uloge_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Uloge_SelectAll_Result>("esp_Uloge_SelectAll");
        }
    
        public virtual ObjectResult<esp_VrsteProizvoda_SelectAll_Result> esp_VrsteProizvoda_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_VrsteProizvoda_SelectAll_Result>("esp_VrsteProizvoda_SelectAll");
        }
    
        public virtual int InsertOcjena(Nullable<System.DateTime> datum, Nullable<int> proizvodID, Nullable<int> kupacID, Nullable<int> ocjena)
        {
            var datumParameter = datum.HasValue ?
                new ObjectParameter("Datum", datum) :
                new ObjectParameter("Datum", typeof(System.DateTime));
    
            var proizvodIDParameter = proizvodID.HasValue ?
                new ObjectParameter("ProizvodID", proizvodID) :
                new ObjectParameter("ProizvodID", typeof(int));
    
            var kupacIDParameter = kupacID.HasValue ?
                new ObjectParameter("KupacID", kupacID) :
                new ObjectParameter("KupacID", typeof(int));
    
            var ocjenaParameter = ocjena.HasValue ?
                new ObjectParameter("ocjena", ocjena) :
                new ObjectParameter("ocjena", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertOcjena", datumParameter, proizvodIDParameter, kupacIDParameter, ocjenaParameter);
        }
    
        public virtual ObjectResult<kupciPoProizvoidu_Result> kupciPoProizvoidu(Nullable<int> proizvodID)
        {
            var proizvodIDParameter = proizvodID.HasValue ?
                new ObjectParameter("ProizvodID", proizvodID) :
                new ObjectParameter("ProizvodID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<kupciPoProizvoidu_Result>("kupciPoProizvoidu", proizvodIDParameter);
        }
    
        public virtual ObjectResult<NarudzbaLast_Result> NarudzbaLast()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NarudzbaLast_Result>("NarudzbaLast");
        }
    
        public virtual ObjectResult<ProizvodById_Result> ProizvodById(Nullable<int> proizvodID)
        {
            var proizvodIDParameter = proizvodID.HasValue ?
                new ObjectParameter("proizvodID", proizvodID) :
                new ObjectParameter("proizvodID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProizvodById_Result>("ProizvodById", proizvodIDParameter);
        }
    
        public virtual ObjectResult<Recommended_Result> Recommended(Nullable<int> proizvodID)
        {
            var proizvodIDParameter = proizvodID.HasValue ?
                new ObjectParameter("proizvodID", proizvodID) :
                new ObjectParameter("proizvodID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Recommended_Result>("Recommended", proizvodIDParameter);
        }
    
        public virtual ObjectResult<Select_ByVrstaProizvoda_Result> Select_ByVrstaProizvoda(Nullable<int> vrstaID)
        {
            var vrstaIDParameter = vrstaID.HasValue ?
                new ObjectParameter("VrstaID", vrstaID) :
                new ObjectParameter("VrstaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_ByVrstaProizvoda_Result>("Select_ByVrstaProizvoda", vrstaIDParameter);
        }
    
        public virtual ObjectResult<selectAllIzlazi_Result> selectAllIzlazi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectAllIzlazi_Result>("selectAllIzlazi");
        }
    
        public virtual ObjectResult<serachByNazivmeni_Result> serachByNazivmeni(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<serachByNazivmeni_Result>("serachByNazivmeni", nazivParameter);
        }
    
        public virtual int UpdateMeni(Nullable<int> menidID, string naziv, string opis, Nullable<int> korisnikID)
        {
            var menidIDParameter = menidID.HasValue ?
                new ObjectParameter("MenidID", menidID) :
                new ObjectParameter("MenidID", typeof(int));
    
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var opisParameter = opis != null ?
                new ObjectParameter("Opis", opis) :
                new ObjectParameter("Opis", typeof(string));
    
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("KorisnikID", korisnikID) :
                new ObjectParameter("KorisnikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateMeni", menidIDParameter, nazivParameter, opisParameter, korisnikIDParameter);
        }
    
        public virtual ObjectResult<usp_SelectAllJediniceMjere_Result> usp_SelectAllJediniceMjere()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectAllJediniceMjere_Result>("usp_SelectAllJediniceMjere");
        }
    
        public virtual int usp_SelectAllSkladista()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SelectAllSkladista");
        }
    
        public virtual ObjectResult<usp_SelectAllVrstaProizvoda_Result> usp_SelectAllVrstaProizvoda()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectAllVrstaProizvoda_Result>("usp_SelectAllVrstaProizvoda");
        }
    
        public virtual ObjectResult<esp_Kupci_SelectByKorisnickoIme1_Result> esp_Kupci_SelectByKorisnickoIme1(string korisnickoIme)
        {
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Kupci_SelectByKorisnickoIme1_Result>("esp_Kupci_SelectByKorisnickoIme1", korisnickoImeParameter);
        }
    
        public virtual ObjectResult<AllProizvodiVjezba1_Result> AllProizvodiVjezba1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllProizvodiVjezba1_Result>("AllProizvodiVjezba1");
        }
    
        public virtual ObjectResult<esp_Proizvodi_SelectByJedinicaMjere_Result> esp_Proizvodi_SelectByJedinicaMjere(Nullable<int> jedinicaMjereID)
        {
            var jedinicaMjereIDParameter = jedinicaMjereID.HasValue ?
                new ObjectParameter("JedinicaMjereID", jedinicaMjereID) :
                new ObjectParameter("JedinicaMjereID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Proizvodi_SelectByJedinicaMjere_Result>("esp_Proizvodi_SelectByJedinicaMjere", jedinicaMjereIDParameter);
        }
    
        public virtual ObjectResult<Proizvodi_SelectByJedinicaMjere_Result> Proizvodi_SelectByJedinicaMjere(Nullable<int> jedinicaMjereID)
        {
            var jedinicaMjereIDParameter = jedinicaMjereID.HasValue ?
                new ObjectParameter("JedinicaMjereID", jedinicaMjereID) :
                new ObjectParameter("JedinicaMjereID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proizvodi_SelectByJedinicaMjere_Result>("Proizvodi_SelectByJedinicaMjere", jedinicaMjereIDParameter);
        }
    
        public virtual ObjectResult<AllNarudzbe_Result> AllNarudzbe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllNarudzbe_Result>("AllNarudzbe");
        }
    
        public virtual ObjectResult<esp_Proizvodi_SelectByNaziv_Result> esp_Proizvodi_SelectByNaziv(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Proizvodi_SelectByNaziv_Result>("esp_Proizvodi_SelectByNaziv", nazivParameter);
        }
    }
}
