//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IB150218_APII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudzbe()
        {
            this.Izlazis = new HashSet<Izlazi>();
            this.NarudzbaStavkes = new HashSet<NarudzbaStavke>();
        }
    
        public int NarudzbaID { get; set; }
        public string BrojNarudzbe { get; set; }
        public int KupacID { get; set; }
        public System.DateTime Datum { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> Otkazano { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izlazi> Izlazis { get; set; }
        public virtual Kupci Kupci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NarudzbaStavke> NarudzbaStavkes { get; set; }
    }
}
